# Generated by Django 3.1.6 on 2021-03-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createrss',
            name='url',
            field=models.TextField(verbose_name='Rss Url'),
        ),
    ]
